# Generated by Django 4.2.7 on 2023-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_fname', models.CharField(max_length=20)),
                ('e_lname', models.CharField(max_length=20)),
                ('e_contact', models.CharField(max_length=13)),
                ('e_address', models.CharField(max_length=250)),
                ('e_email', models.EmailField(max_length=100)),
                ('e_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
