# Generated by Django 4.2.7 on 2023-11-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_lname',
            field=models.CharField(max_length=50),
        ),
    ]
